# This is a basic workflow to help you get started with Actions

name: Coverage

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # check gradle dependencies  
      - name: Check gradle dependencies
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
        
      - name: After test
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_SECRET }}
